server:
  port: 4000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fanyunai?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: # 如果没有密码可以留空
      client-type: lettuce
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

mybatis:
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: MySuperSecretKey1234567890123456
  expiration: 3600000

logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
